### PR TITLE
Disable tracer particles at run time

### LINKED ISSUE #155: Compile with CustomFunc(Particles) in Debug Mode
Hi

When using IAMR, I wrote a set of particle processing methods through the particle module of amrex. When compiling, I encountered the following problem: in the GNUmakefile, `USE_PARTICLES = TRUE` is enabled, but the original particle part in IAMR will also be activated accordingly. However, if I do use `USE_PARTICLES = FALSE` and instead only include `$(AMREX_HOME)/Src/Particle/Make.package`, it can compile successfully in Release mode, but encounters compilation errors in DEBUG mode. Here is a partial compilation error message.

```
../../../amrex/Src/Particle/AMReX_ParticleUtil.H:32:44: error: ‘IsParticleIterator’ was not declared in this scope; did you mean ‘IsMultiFabIterator’?
   32 | template <class Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value, int> foo = 0>
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            IsMultiFabIterator
../../../amrex/Src/Particle/AMReX_ParticleUtil.H:32:71: error: template argument 1 is invalid
   32 | plate <class Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value, int> foo = 0>
      |                                                                    ^

../../../amrex/Src/Particle/AMReX_ParticleUtil.H:32:86: error: ‘foo’ does not name a type
   32 |  Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value, int> foo = 0>
      |                                                                       ^~~

Compiling hydro_compute_edgestate_and_flux.cpp ...
../../../amrex/Src/Particle/AMReX_ParticleUtil.H:50:44: error: ‘IsParticleIterator’ was not declared in this scope; did you mean ‘IsMultiFabIterator’?
   50 | template <class Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value && !Iterator::ContainerType::ParticleType::is_soa_particle, int> foo = 0>
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            IsMultiFabIterator
../../../amrex/Src/Particle/AMReX_ParticleUtil.H:50:71: error: template argument 1 is invalid
   50 | plate <class Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value && !Iterator::ContainerType::ParticleType::is_soa_particle, int> foo = 0>
      |                                                                    ^

../../../amrex/Src/Particle/AMReX_ParticleUtil.H:50:80: error: expected ‘>’ before ‘&&’ token
   50 | ass Iterator, std::enable_if_t<IsParticleIterator<Iterator>::value && !Iterator::ContainerType::ParticleType::is_soa_particle, int> foo = 0>
      |                                                                    ^~

../../../amrex/Src/Particle/AMReX_ParticleUtil.H:50:145: error: ‘foo’ does not name a type
   50 | alue && !Iterator::ContainerType::ParticleType::is_soa_particle, int> foo = 0>
      |                                                                       ^~~

```
I hope to have more flexibility here by enabling the particle calculation part in IAMR through the addition of other macro compilation conditions, such as `-DIAMR_PARTICLE`, instead of it being activated simply by setting `USE_PARTICLES = TRUE`.

### PR DESCRIPTION
**Pull request by WeiqunZhang**
There is a runtime parameter `particles.do_nspc_particles` for disabling particles. But it was not used everywhere. This commit fixes it.

### CODE REVIEW

File: Source/NavierStokes.cpp [hunk 1]
```diff
@@ -478,7 +478,9 @@ NavierStokes::initData ()
     }
 
 #ifdef AMREX_PARTICLES
-    initParticleData ();
+    if (do_nspc) {
```
Comment (cgilet) [inline Source/NavierStokes.cpp:481]: Do we really need this if you've added `if (!do_nspc) { return; }` in NSB::initParticleData? I suppose it doesn't really matter though.

**Review by cgilet — APPROVED** [review]

File: Source/NavierStokes.cpp (hunk 1 above)
Comment (WeiqunZhang) [reply Source/NavierStokes.cpp:481]: Right. It does not matter.
